# fly.toml app configuration file generated for sei-project-3-learn-it on 2023-04-29T18:33:10+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sei-project-3-learn-it"
primary_region = "syd"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
